import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
create table auth.mfa_factors(user_id uuid,status text); create function auth.jwt() returns jsonb language sql as $$select '{"aal":"aal1"}'::jsonb$$;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid,name text,bucket_id text);
alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
grant usage on schema auth,public,storage to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
let sql=await readFile(new URL('../supabase/01-schema.sql',import.meta.url),'utf8');sql=sql.replace('create extension if not exists pgcrypto;','');
await db.exec(sql);
const admin='00000000-0000-4000-8000-000000000001',seller='00000000-0000-4000-8000-000000000002',buyer='00000000-0000-4000-8000-000000000003',other='00000000-0000-4000-8000-000000000004';
await db.query(`insert into auth.users values($1,'{"name":"admin"}'),($2,'{"name":"seller","phone":"+50760000000"}'),($3,'{"name":"buyer"}'),($4,'{"name":"other"}')`,[admin,seller,buyer,other]);await db.query('insert into administrators values(true,$1)',[admin]);
async function as(u,fn){await db.query("select set_config('test.uid',$1,false)",[u]);await db.exec('set role authenticated');try{return await fn()}finally{await db.exec('reset role')}}
const mutate=async(op,payload)=>(await db.query('select public.mutate($1,$2) result',[op,JSON.stringify(payload)])).rows[0].result;
let pid,oid,cid;
test('identidad única y sin lectura de perfiles privados ajenos',async()=>{const all=await db.query('select customer_id from profiles');assert.equal(new Set(all.rows.map(x=>x.customer_id)).size,4);await as(buyer,async()=>{assert.equal((await db.query('select * from profiles')).rows.length,1);await assert.rejects(()=>db.query('update profiles set verified=true'));await assert.rejects(()=>db.query('insert into administrators values(false,$1)',[buyer]))})});
test('publicar, moderar y prohibir edición ajena',async()=>{pid=(await as(seller,()=>mutate('product',{name:'Artículo prueba',price:10,category:'Otros',variants:[{name:'Única',stock:3}],images:[]}))).id;await as(buyer,async()=>{assert.equal((await db.query('select * from products')).rows.length,0);await assert.rejects(()=>mutate('product',{id:pid,name:'Ataque',price:1,category:'Otros',variants:[{name:'Única',stock:100}]}));await assert.rejects(()=>mutate('admin_product',{id:pid,status:'approved'}))});await as(admin,()=>mutate('admin_product',{id:pid,status:'approved'}))});
test('precios del servidor, reserva y restauración al cancelar',async()=>{const list=await as(buyer,()=>mutate('orders',{items:[{product_id:pid,variant:'Única',quantity:2,price:0.01}]}));oid=list[0];assert.equal(Number((await db.query('select total from orders where id=$1',[oid])).rows[0].total),20);await as(seller,()=>mutate('order_status',{id:oid,status:'accepted'}));assert.equal((await db.query('select variants from products where id=$1',[pid])).rows[0].variants[0].stock,1);await as(other,()=>assert.rejects(()=>mutate('order_status',{id:oid,status:'cancelled'})));await as(seller,()=>mutate('order_status',{id:oid,status:'cancelled'}));assert.equal((await db.query('select variants from products where id=$1',[pid])).rows[0].variants[0].stock,3)});
test('chat privado, bloqueo y revisión administrativa auditada',async()=>{cid=(await as(buyer,()=>mutate('chat',{product_id:pid}))).id;await as(buyer,()=>mutate('message',{conversation_id:cid,body:'Hola vendedor'}));await as(other,async()=>{assert.equal((await db.query('select * from messages')).rows.length,0);await assert.rejects(()=>mutate('message',{conversation_id:cid,body:'Intrusión'}))});await as(admin,async()=>assert.equal((await db.query('select * from messages')).rows.length,0));await as(seller,()=>mutate('block',{id:buyer}));await as(buyer,()=>assert.rejects(()=>mutate('message',{conversation_id:cid,body:'Bloqueado'})));await as(buyer,()=>mutate('report',{kind:'chat',conversation_id:cid,reason:'Prueba de reporte'}));const report=(await db.query('select id from reports')).rows[0].id;await as(admin,async()=>{assert.equal((await db.query('select * from review_report_chat($1)',[report])).rows.length,1);assert.ok((await db.query("select * from audit where action='review_report_chat'")).rows.length)})});
test('reseñas solo después de entrega y suspensión efectiva',async()=>{await as(buyer,()=>assert.rejects(()=>mutate('review',{order_id:oid,rating:5,body:'No entregado'})));await as(admin,()=>mutate('admin_user',{id:seller,suspended:true,verified:false}));await as(buyer,async()=>assert.equal((await db.query('select * from products')).rows.length,0));await as(seller,()=>assert.rejects(()=>mutate('favorite',{id:pid})))})
test('cupón de vendedor y flujo completo de compra',async()=>{await as(admin,()=>mutate('admin_user',{id:seller,suspended:false,verified:true}));await as(seller,()=>mutate('coupon',{code:'MAVI10',percent:10,expires_at:'2099-01-01T00:00:00Z'}));let id=(await as(buyer,()=>mutate('orders',{coupon:'MAVI10',items:[{product_id:pid,variant:'Única',quantity:1}]})))[0];assert.equal(Number((await db.query('select total from orders where id=$1',[id])).rows[0].total),9);await as(seller,()=>mutate('order_status',{id,status:'accepted'}));await as(buyer,()=>assert.rejects(()=>mutate('order_status',{id,status:'paid'})));await as(seller,()=>mutate('order_status',{id,status:'paid'}));await as(seller,()=>mutate('order_status',{id,status:'shipped',tracking:'Paquete 123'}));await as(buyer,()=>mutate('order_status',{id,status:'delivered'}));await as(buyer,()=>mutate('review',{order_id:id,rating:5,body:'Llegó bien'}));assert.equal((await db.query('select * from reviews where order_id=$1',[id])).rows.length,1);await as(buyer,()=>assert.rejects(()=>mutate('review',{order_id:id,rating:5,body:'Duplicada'}))) });
test('carrito inválido revierte por completo y MFA bloquea cambios sin segundo factor',async()=>{await as(buyer,()=>assert.rejects(()=>mutate('orders',{items:[{product_id:'00000000-0000-4000-8000-000000000099',variant:'Única',quantity:1}]})));await db.query("insert into auth.mfa_factors values($1,'verified')",[admin]);await as(admin,()=>assert.rejects(()=>mutate('admin_settings',{name:'Ataque'})))});
