import { createClient } from '@supabase/supabase-js';
import './style.css';
const env=import.meta.env;
const configured=Boolean(env.VITE_SUPABASE_URL&&!env.VITE_SUPABASE_URL.includes('TU-PROYECTO')&&env.VITE_SUPABASE_ANON_KEY);
const db=configured?createClient(env.VITE_SUPABASE_URL,env.VITE_SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-PA',{style:'currency',currency:'USD'}).format(n||0);
const date=d=>new Date(d).toLocaleString('es-PA');
const safe=s=>/^(https:\/\/|\/logo\.png$)/.test(s||'')?s:'/logo.png';
const img=(s,cls='',alt='Producto')=>`<img class="${cls}" src="${esc(safe(s))}" alt="${esc(alt)}" loading="lazy">`;
const labels={pending:'Pendiente',approved:'Publicado',draft:'Borrador',paused:'Pausado',archived:'Archivado',rejected:'Rechazado',accepted:'Aceptado',paid:'Pago confirmado',shipped:'Enviado',delivered:'Entregado',cancelled:'Cancelado',open:'Abierto',resolved:'Resuelto'};
let user=null,profile=null,admin=false,settings={name:'MAVI\'S SHOP',categories:['Tecnología','Hogar','Moda','Belleza','Deportes','Otros'],logo:'/logo.png',policies:'Los pagos y las entregas se coordinan directamente con cada vendedor.',contact:''}, timer, generation=0;
let cart=[];try{cart=JSON.parse(localStorage.getItem('mavi-cart')||'[]');if(!Array.isArray(cart))cart=[]}catch{}
const saveCart=()=>localStorage.setItem('mavi-cart',JSON.stringify(cart));
const toast=(m)=>{const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(timer);timer=setTimeout(()=>t.style.display='none',5500)};
const go=p=>{location.hash=p};
const route=()=>location.hash.slice(1).split('?')[0]||'/';
const query=()=>new URLSearchParams(location.hash.split('?')[1]||'');
const btn=(text,act,id='',cls='secondary')=>`<button class="${cls}" data-action="${act}" data-id="${esc(id)}">${text}</button>`;
const field=(label,name,value='',type='text',extra='')=>`<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const area=(label,name,value='')=>`<div class="field"><label for="${name}">${label}</label><textarea id="${name}" name="${name}">${esc(value)}</textarea></div>`;
const check=(label,name,value)=>`<label class="row field"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;
const select=(label,name,options,value)=>`<div class="field"><label for="${name}">${label}</label><select name="${name}" id="${name}">${options.map(o=>`<option value="${esc(typeof o==='string'?o:o[0])}" ${(typeof o==='string'?o:o[0])===value?'selected':''}>${esc(typeof o==='string'?o:o[1])}</option>`).join('')}</select></div>`;
const badge=s=>`<span class="badge">${esc(labels[s]||s)}</span>`;
const empty=(title,text,action='')=>`<div class="empty">${img('/logo.png','','MAVI\'S SHOP')}<h3>${title}</h3><p>${text}</p>${action}</div>`;
const brand=()=>`<a class="brand" href="#/">${img(settings.logo,'','Logo MAVI\'S SHOP')}<span>MAVI'S <em>SHOP</em></span></a>`;
async function rows(table,fn=q=>q){if(!db)return [];const {data,error}=await fn(db.from(table).select('*'));if(error)throw error;return data||[]}
async function rpc(op,payload={}){if(!db)throw Error('Configura Supabase siguiendo INSTRUCCIONES.md para activar esta función.');const {data,error}=await db.rpc('mutate',{op,payload});if(error)throw error;return data}
async function authState(){if(!db)return;const {data}=await db.auth.getSession();user=data.session?.user||null;profile=null;admin=false;if(user){profile=(await rows('profiles',q=>q.eq('id',user.id)))[0];admin=Boolean((await rows('administrators')).length)}}
function layout(content){const r=route();$('#app').innerHTML=`<div class="topbar">Compra y vende · Contacto directo con cada vendedor</div><header class="header">${brand()}<nav aria-label="Principal"><a href="#/shop" class="${r==='/shop'?'active':''}">Tienda</a><a href="#/favorites">Favoritos</a><a href="#/cart">Carrito (${cart.reduce((a,b)=>a+b.quantity,0)})</a>${user?`<a href="#/messages">Mensajes</a><a href="#/account">Mi cuenta</a>${admin?'<a href="#/admin">Administración</a>':''}${btn('Salir','logout','','outline small')}`:'<a href="#/login">Ingresar</a><a class="button coral small" href="#/register">Crear cuenta</a>'}</nav></header><main class="container">${content}</main><footer class="footer"><div class="row between">${brand()}<div class="row"><a href="#/help">Ayuda y preguntas frecuentes</a><a href="#/policies">Políticas y contacto</a></div></div><p class="muted">© ${new Date().getFullYear()} ${esc(settings.name)} · Los pagos y las entregas se acuerdan con el vendedor.</p></footer>`;document.title=`${settings.name} | Compra, vende, conecta`;document.querySelector('link[rel=icon]').href=safe(settings.logo)}
const accountNav=()=>`<div class="subnav">${[['/account','Mi perfil'],['/products','Mis productos'],['/orders','Mis compras'],['/sales','Mis ventas'],['/coupons','Cupones'],['/messages','Mensajes'],['/notifications','Notificaciones'],['/reports','Reclamos y reportes']].map(([p,t])=>`<a class="${route()===p?'active':''}" href="#${p}">${t}</a>`).join('')}</div>`;
const adminNav=()=>`<div class="subnav">${[['/admin','Resumen'],['/admin/users','Usuarios'],['/admin/products','Publicaciones'],['/admin/orders','Pedidos'],['/admin/reports','Reportes'],['/admin/settings','Configuración'],['/admin/audit','Historial']].map(([p,t])=>`<a class="${route()===p?'active':''}" href="#${p}">${t}</a>`).join('')}</div>`;
const card=p=>`<article class="card"><a href="#/product/${p.id}">${img(p.images?.[0])}<div class="cardbody"><span class="muted">${esc(p.category)}</span><h3>${esc(p.name)}</h3><div class="price">${money(p.price)} ${p.previous_price>p.price?`<del>${money(p.previous_price)}</del>`:''}</div><p class="muted">${p.variants.reduce((s,v)=>s+Number(v.stock),0)>0?'Disponible':'Agotado'}</p></div></a></article>`;
const cards=list=>list.length?`<div class="cards">${list.map(card).join('')}</div>`:empty('Aquí comienza algo bueno','Todavía no hay productos publicados. Sé el primero en compartir los tuyos.','<a class="button coral" href="#/product/new">Publicar un producto</a>');
async function upload(file,bucket='products',cid=''){if(!file?.size)return '';if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Usa JPG, PNG o WebP de hasta 5 MB.');const path=`${cid?cid+'/':''}${user.id}/${crypto.randomUUID()}.${file.type.split('/')[1]}`;const {error}=await db.storage.from(bucket).upload(path,file,{contentType:file.type});if(error)throw error;return bucket==='chat'?path:db.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function render(){const g=++generation;try{const r=route();const protectedRoute=['/account','/products','/product/new','/orders','/sales','/messages','/notifications','/reports','/favorites','/coupons'];if((protectedRoute.includes(r)||r.startsWith('/edit/')||r.startsWith('/admin'))&&!user){go('/login');return}if(r.startsWith('/admin')&&!admin){layout(empty('Acceso restringido','Esta sección pertenece al administrador.'));return}let html='';
if(r==='/'){const list=await rows('products',q=>q.eq('status','approved').order('created_at',{ascending:false}).limit(4));html=`<section class="hero"><div><span class="eyebrow">Bienvenido a MAVI\'S SHOP</span><h1>Un lugar para encontrar.<br>Un espacio para vender.</h1><p>Descubre artículos de vendedores independientes. Pregunta, conversa y coordina tu compra directamente con quien vende.</p><div class="row"><a class="button coral" href="#/shop">Explorar la tienda</a><a class="button outline" href="#/${user?'product/new':'register'}">Quiero vender</a></div></div><div class="hero-logo">${img('/logo.png','','Logo MAVI\'S SHOP')}</div></section><div class="benefits"><div><strong>01 · Encuentra lo que buscas</strong><span class="muted">Un catálogo, muchas posibilidades.</span></div><div><strong>02 · Habla con el vendedor</strong><span class="muted">Chat privado o WhatsApp, tú eliges.</span></div><div><strong>03 · Coordina tu compra</strong><span class="muted">Acuerda el pago y la entrega directamente.</span></div></div><div class="row between"><h2>Explora por categoría</h2><a class="link" href="#/shop">Ver toda la tienda</a></div><div class="subnav">${settings.categories.map(c=>`<a href="#/shop?category=${encodeURIComponent(c)}">${esc(c)}</a>`).join('')}</div><h2>Recién llegados</h2>${cards(list)}`}
else if(r==='/shop'||r==='/favorites'){let list=await rows('products',q=>q.eq('status','approved').order('created_at',{ascending:false}));if(r==='/favorites'){const f=await rows('favorites');list=list.filter(p=>f.some(v=>v.product_id===p.id))}const q=query(),term=q.get('q')||'',cat=q.get('category')||'',brandFilter=q.get('brand')||'';const brands=[...new Set(list.map(p=>p.brand).filter(Boolean))];list=list.filter(p=>(!term||(p.name+' '+p.description+' '+p.brand).toLowerCase().includes(term.toLowerCase()))&&(!cat||p.category===cat)&&(!brandFilter||p.brand===brandFilter)&&(!q.get('min')||p.price>=Number(q.get('min')))&&(!q.get('max')||p.price<=Number(q.get('max')))&&(!q.get('stock')||p.variants.some(v=>v.stock>0)));if(q.get('sort')==='low')list.sort((a,b)=>a.price-b.price);if(q.get('sort')==='high')list.sort((a,b)=>b.price-a.price);html=`<span class="eyebrow">MAVI'S / ${r==='/favorites'?'GUARDADOS':'CATÁLOGO'}</span><h1>${r==='/favorites'?'Tus favoritos':'La tienda de todos'}</h1><form id="search" class="panel"><div class="filters">${field('Buscar','q',term,'search','placeholder="¿Qué estás buscando?"')}${select('Categoría','category',[['','Todas'],...settings.categories],cat)}${select('Marca','brand',[['','Todas'],...brands],brandFilter)}${select('Ordenar','sort',[['new','Más recientes'],['low','Menor precio'],['high','Mayor precio']],q.get('sort')||'new')}</div><div class="row">${field('Precio mínimo','min',q.get('min')||'','number','min="0" step="0.01"')}${field('Precio máximo','max',q.get('max')||'','number','min="0" step="0.01"')}${check('Solo disponibles','stock',q.has('stock'))}<button>Buscar</button></div></form><p class="muted">${list.length} productos</p>${cards(list)}`}
else if(r==='/login'||r==='/register'||r==='/forgot'||r==='/reset'){const reg=r==='/register',forgot=r==='/forgot',reset=r==='/reset';html=`<section class="panel auth">${brand()}<h2>${reg?'Crea tu cuenta':forgot?'Recupera tu acceso':reset?'Nueva contraseña':'Qué bueno verte de nuevo'}</h2><p class="muted">${reg?'Compra, publica y conversa desde una sola cuenta.':'Tu espacio en MAVI\'S SHOP.'}</p>${!configured?'<p class="notice">Vista previa. Configura Supabase con la guía incluida para activar las cuentas.</p>':''}<form id="auth" data-mode="${r.slice(1)}">${reg?field('Nombre completo','name','','text','required maxlength="100"')+field('WhatsApp con código de país','phone','+507','tel','required pattern="\\+[1-9][0-9]{7,14}" placeholder="+50760000000"')+'<p class="muted">Tu número será accesible desde el botón WhatsApp de tus productos.</p>':''}${!reset?field(reg||forgot?'Correo electrónico':'Correo o usuario admin','email','',reg||forgot?'email':'text','required autocomplete="username"'):''}${!forgot?field('Contraseña','password','','password',`required minlength="12" autocomplete="${reg||reset?'new-password':'current-password'}"`):''}${reg?'<label class="row field"><input type="checkbox" required>Acepto las <a class="link" href="#/policies">políticas de la tienda</a>.</label>':''}<button class="coral">${reg?'Crear mi cuenta':forgot?'Enviar enlace':reset?'Guardar contraseña':'Ingresar'}</button></form><div class="row" style="margin-top:20px"><a class="link" href="#/forgot">Olvidé mi contraseña</a><a class="link" href="#/${reg?'login':'register'}">${reg?'Ya tengo cuenta':'Crear cuenta'}</a></div></section>`}
else if(r==='/account'){const p=profile;const blocks=await rows('blocks');html=`${accountNav()}<h1>Mi perfil</h1><p class="muted">ID de cliente: <strong>${esc(p.customer_id)}</strong></p>${p.suspended?'<p class="notice">Tu cuenta está suspendida. Contacta con la administración.</p>':''}<form id="profile" class="panel"><div class="row">${img(p.avatar,'avatar','Foto de perfil')}<div><h3>${esc(p.name)}</h3>${p.verified?badge('Vendedor verificado'):badge('Correo confirmado')}</div></div><div class="formgrid">${field('Nombre público','name',p.name,'text','required maxlength="100"')}${field('WhatsApp público','phone',p.phone,'tel','required pattern="\\+[1-9][0-9]{7,14}"')}${area('Sobre ti o tu negocio','bio',p.bio)}${field('Foto o logo','avatarFile','','file','accept="image/png,image/jpeg,image/webp"')}</div>${check('Estoy de vacaciones: pausar nuevas compras','vacation',p.vacation)}${check('Recibir avisos dentro de la página','notifications',p.notifications)}${check('Recibir también avisos por correo','email_notifications',p.email_notifications)}<button>Guardar perfil</button></form><div class="panel"><h3>Seguridad</h3><p class="muted">Correo privado: ${esc(user.email)}</p><div class="row"><a class="button secondary" href="#/forgot">Cambiar contraseña</a>${btn('Activar verificación en dos pasos','mfa')}</div></div><div class="panel"><h3>Contactos bloqueados</h3>${blocks.length?blocks.map(b=>`<p>${esc(b.blocked_id)} ${btn('Desbloquear','block',b.blocked_id)}</p>`).join(''):'<p class="muted">No tienes contactos bloqueados.</p>'}</div>`}
else if(r==='/products'){const list=await rows('products',q=>q.eq('seller_id',user.id).order('created_at',{ascending:false}));html=`${accountNav()}<div class="row between"><h1>Mis productos</h1><a class="button coral" href="#/product/new">+ Publicar producto</a></div>${list.some(p=>p.variants.some(v=>v.stock<=3))?'<p class="notice">Tienes variantes con 3 unidades o menos. Revisa el inventario antes de aceptar nuevos pedidos.</p>':''}${list.length?`<div class="panel scroll"><table><thead><tr><th>Producto</th><th>Estado</th><th>Precio</th><th>Stock</th><th>Acciones</th></tr></thead><tbody>${list.map(p=>`<tr><td>${esc(p.name)}</td><td>${badge(p.status)}</td><td>${money(p.price)}</td><td>${p.variants.map(v=>esc(v.name)+': '+v.stock).join('<br>')}</td><td><a class="button small secondary" href="#/edit/${p.id}">Editar</a></td></tr>`).join('')}</tbody></table></div>`:empty('Tu escaparate está listo','Publica tu primer producto o guárdalo como borrador.')}`}
else if(r==='/product/new'||r.startsWith('/edit/')){const p=r.startsWith('/edit/')?(await rows('products',q=>q.eq('id',r.split('/')[2])))[0]:{variants:[{name:'Única',stock:0}],images:[]};if(!p)throw Error('Producto no encontrado');html=`${accountNav()}<h1>${p.id?'Editar producto':'Publicar producto'}</h1><form id="product-form" data-id="${p.id||''}" class="panel"><div class="formgrid">${field('Nombre','name',p.name,'text','required maxlength="160"')}${select('Categoría','category',settings.categories,p.category)}${field('Precio USD','price',p.price,'number','required min="0.01" step="0.01"')}${field('Precio anterior (opcional)','previous_price',p.previous_price,'number','min="0.01" step="0.01"')}${field('Marca','brand',p.brand)}${select('Guardar como','status',[['pending','Enviar a revisión / publicar'],['draft','Borrador'],['paused','Pausado'],['archived','Archivado']],['draft','paused','archived'].includes(p.status)?p.status:'pending')}${area('Descripción','description',p.description)}${area('Características y medidas','specs',p.specs)}${area('Zonas, costo y tiempo de entrega','shipping',p.shipping)}${area('Garantía y condiciones de devolución','warranty',p.warranty)}</div><h3>Variantes e inventario</h3><p class="muted">Una línea por variante: nombre | existencias. Ejemplo: Azul / M | 10. Para artículos sin variantes: Única | 10.</p>${area('Variantes','variants',p.variants.map(v=>v.name+' | '+v.stock).join('\n'))}<h3>Fotografías</h3><div class="row">${p.images.map(url=>`<label>${img(url,'thumb')}<input type="checkbox" name="keepImage" value="${esc(url)}" checked> Conservar</label>`).join('')}</div>${field('Agregar fotos (máximo 8 en total, 5 MB cada una)','photos','','file','multiple accept="image/jpeg,image/png,image/webp"')}<button class="coral">Guardar producto</button></form>`}
else if(r.startsWith('/product/')){const p=(await rows('products',q=>q.eq('id',r.split('/')[2])))[0];if(!p)throw Error('Producto no disponible');const s=(await rows('seller_public',q=>q.eq('id',p.seller_id)))[0];const reviews=await rows('reviews',q=>q.eq('seller_id',p.seller_id));const {data:phone,error}=await db.rpc('seller_contact',{pid:p.id});if(error)throw error;html=`<p class="muted"><a href="#/shop">Tienda</a> / ${esc(p.category)}</p><div class="detail"><div>${img(p.images[0],'productimage','Foto de '+p.name)}<div class="row">${p.images.map(i=>`<button class="outline small" data-action="image" data-id="${esc(i)}">${img(i,'thumb')}</button>`).join('')}</div></div><div>${badge(p.category)}<h1>${esc(p.name)}</h1><p class="price">${money(p.price)} ${p.previous_price>p.price?`<del>${money(p.previous_price)}</del>`:''}</p><p class="pre muted">${esc(p.description)}</p><p>Vendido por <a class="link" href="#/seller/${s.id}">${esc(s.name)}</a> ${s.verified?badge('Verificado'):''}</p>${s.vacation?'<p class="notice">Este vendedor está de vacaciones.</p>':''}<form id="add-cart" data-id="${p.id}">${select('Variante','variant',p.variants.map(v=>[v.name,`${v.name} · ${v.stock} disponibles`]),p.variants[0].name)}${field('Cantidad','quantity',1,'number','required min="1" max="999"')}<button class="coral" ${s.vacation||p.status!=='approved'?'disabled':''}>Agregar al carrito</button></form><div class="row" style="margin:18px 0">${phone?`<a class="button outline" target="_blank" rel="noopener noreferrer" href="https://wa.me/${esc(phone.replace(/\D/g,''))}?text=${encodeURIComponent('Hola, me interesa '+p.name+' en MAVI\'S SHOP: '+location.href)}">WhatsApp</a>`:''}${btn('Chat con el vendedor','chat',p.id)}${btn('♥ Guardar / quitar','favorite',p.id)}${btn('Compartir','share')}</div><p class="muted">El pago y la entrega se coordinan con el vendedor.</p>${btn('Reportar producto','report-product',p.id,'outline small')}</div></div><div class="panel"><h3>Características</h3><p class="pre">${esc(p.specs)||'Consulta al vendedor.'}</p><h3>Entrega</h3><p class="pre">${esc(p.shipping)||'A coordinar con el vendedor.'}</p><h3>Garantía y devoluciones</h3><p class="pre">${esc(p.warranty)||'Consulta las condiciones con el vendedor antes de pagar.'}</p></div><h2>Opiniones sobre el vendedor</h2>${reviewList(reviews)}`}
else if(r.startsWith('/seller/')){const id=r.split('/')[2],s=(await rows('seller_public',q=>q.eq('id',id)))[0];if(!s)throw Error('Vendedor no encontrado');const list=await rows('products',q=>q.eq('seller_id',id).eq('status','approved'));html=`<section class="panel"><div class="row">${img(s.avatar,'avatar')}<div><h1>${esc(s.name)}</h1>${s.verified?badge('Vendedor verificado'):''}${s.vacation?badge('De vacaciones'):''}</div></div><p class="pre muted">${esc(s.bio)}</p><div class="row">${btn('Compartir perfil','share')}${btn('Bloquear / desbloquear','block',s.id)}${btn('Reportar vendedor','report-user',s.id)}</div></section><h2>Productos del vendedor</h2>${cards(list)}<h2>Opiniones</h2>${reviewList(await rows('reviews',q=>q.eq('seller_id',id)))}`}
else if(r==='/cart'){html=`<h1>Tu carrito</h1><p class="muted">Se enviará una solicitud independiente a cada vendedor. No se cobra dentro de MAVI\'S SHOP.</p>${cart.length?`<div class="panel scroll"><table><thead><tr><th>Producto</th><th>Variante</th><th>Cantidad</th><th>Subtotal estimado</th><th></th></tr></thead><tbody>${cart.map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${esc(p.variant)}</td><td><input aria-label="Cantidad ${esc(p.name)}" type="number" min="1" max="999" value="${p.quantity}" data-cart="${i}"></td><td>${money(p.price*p.quantity)}</td><td>${btn('Eliminar','cart-remove',String(i),'danger small')}</td></tr>`).join('')}</tbody></table><h2>Subtotal: ${money(cart.reduce((s,p)=>s+p.price*p.quantity,0))}</h2><p class="muted">Envío a convenir. El servidor confirmará los precios actuales al enviar.</p><form id="checkout">${field('Cupón (opcional, aplica al vendedor que lo emitió)','coupon')}${area('Nota para los vendedores (zona de entrega o consulta)','note')}<button class="coral">Enviar solicitudes de pedido</button></form></div>`:empty('Tu carrito está vacío','Explora la tienda y guarda lo que te guste.','<a class="button" href="#/shop">Ir a la tienda</a>')}`}
else if(r==='/orders'||r==='/sales'||r==='/admin/orders'){const sales=r==='/sales',all=r==='/admin/orders';const list=await rows('orders',q=>all?q.order('created_at',{ascending:false}):q.eq(sales?'seller_id':'buyer_id',user.id).order('created_at',{ascending:false}));const names=await rows('seller_public');html=`${all?adminNav():accountNav()}<h1>${all?'Todos los pedidos':sales?'Mis ventas':'Mis compras'}</h1>${sales?stats([['Pedidos',list.length],['Entregados',list.filter(o=>o.status==='delivered').length],['Ventas entregadas',money(list.filter(o=>o.status==='delivered').reduce((s,o)=>s+Number(o.total)+Number(o.shipping_fee),0))],['Resultado registrado',money(list.filter(o=>o.status==='delivered').reduce((s,o)=>s+Number(o.total)+Number(o.shipping_fee)-Number(o.expenses),0))]]):''}${list.length?list.map(o=>orderCard(o,names)).join(''):empty('Aún no hay pedidos',sales?'Las solicitudes de tus compradores aparecerán aquí.':'Tus solicitudes de compra aparecerán aquí.')}`}
else if(r==='/messages'){const chats=await rows('conversations',q=>q.order('created_at',{ascending:false}));const names=await rows('seller_public');const unread=await rows('messages',q=>q.is('read_at',null).neq('sender_id',user.id));const cid=query().get('id')||chats[0]?.id;const c=chats.find(c=>c.id===cid);const msgs=c?await rows('messages',q=>q.eq('conversation_id',cid).order('created_at')):[];for(const m of msgs){if(m.image){const {data}=await db.storage.from('chat').createSignedUrl(m.image,600);m.url=data?.signedUrl}}html=`${accountNav()}<h1>Conversaciones</h1>${chats.length?`<div class="chatlayout"><aside class="panel chatlist">${chats.map(c=>`<a href="#/messages?id=${c.id}"><strong>${esc(names.find(n=>n.id===(c.buyer_id===user.id?c.seller_id:c.buyer_id))?.name||'Usuario')}</strong><p class="muted">${unread.filter(m=>m.conversation_id===c.id).length} sin leer</p></a>`).join('')}</aside><section class="panel">${c?`<div class="row between"><a class="link" href="#/product/${c.product_id}">Ver producto</a><div class="row">${btn('Reportar','report-chat',c.id,'outline small')}${btn('Bloquear / desbloquear','block',c.buyer_id===user.id?c.seller_id:c.buyer_id,'outline small')}</div></div><div class="messages">${msgs.map(m=>`<div class="bubble ${m.sender_id===user.id?'mine':''}">${esc(m.body)}${m.url?img(m.url):''}<time>${date(m.created_at)}${m.sender_id===user.id&&m.read_at?' · Leído':''}</time></div>`).join('')||'<p class="muted">Comienza la conversación.</p>'}</div><form id="message" data-id="${c.id}">${field('Mensaje','body','','text','maxlength="4000" autocomplete="off"')}${field('Adjuntar imagen','image','','file','accept="image/jpeg,image/png,image/webp"')}<button>Enviar mensaje</button></form>`:''}</section></div>`:empty('Todavía no tienes conversaciones','Abre un producto y pulsa “Chat con el vendedor”.')}`;if(c)await rpc('read',{conversation_id:c.id})}
else if(r==='/coupons'){const list=await rows('coupons',q=>q.eq('seller_id',user.id));html=`${accountNav()}<h1>Mis cupones</h1><p class="muted">Comparte un código con tus compradores. Solo descuenta productos de tu tienda.</p><form id="coupon-form" class="panel formgrid">${field('Código','code','','text','required pattern="[A-Za-z0-9_-]{3,30}"')}${field('Descuento %','percent',10,'number','required min="1" max="100"')}${field('Válido hasta','expires_at','','datetime-local','required')}<div class="field"><button>Crear cupón</button></div></form>${list.map(c=>`<div class="panel row between"><div><strong>${esc(c.code)} · ${c.percent}%</strong><p class="muted">Vence ${date(c.expires_at)} · ${c.enabled?'Activo':'Desactivado'}</p></div>${btn(c.enabled?'Desactivar':'Activar','coupon-toggle',c.id)}</div>`).join('')}`}
else if(r==='/notifications'){const list=await rows('notifications',q=>q.order('created_at',{ascending:false}).limit(100));html=`${accountNav()}<div class="row between"><h1>Notificaciones</h1>${btn('Marcar como leídas','read')}</div>${list.length?list.map(n=>`<div class="panel"><p>${!n.read_at?badge('Nuevo'):''} ${esc(n.body)}</p><small class="muted">${date(n.created_at)}</small></div>`).join(''):empty('Estás al día','Aquí aparecerán los avisos de tu cuenta.')}`}
else if(r==='/reports'||r==='/admin/reports'){const list=await rows('reports',q=>q.order('created_at',{ascending:false}));html=`${r.startsWith('/admin')?adminNav():accountNav()}<h1>Reclamos y reportes</h1>${list.length?list.map(v=>`<div class="panel"><div class="row between"><h3>${esc(v.kind==='return'?'Devolución':v.kind)}</h3>${badge(v.status)}</div><p class="pre">${esc(v.reason)}</p>${v.evidence?`<p class="pre muted">Evidencia: ${esc(v.evidence)}</p>`:''}<p class="muted">${date(v.created_at)} · ${esc(v.order_id||v.target_id||v.conversation_id)}</p><p class="pre">${esc(v.resolution)}</p>${admin&&v.conversation_id&&v.status==='open'?btn('Revisar chat reportado','review-chat',v.id):''}${admin?btn('Resolver','resolve-report',v.id):v.kind==='return'&&v.user_id!==user.id?btn('Responder devolución','resolve-return',v.id):''}</div>`).join(''):empty('No hay reportes','Los reportes y solicitudes de devolución aparecerán aquí.')}`}
else if(r==='/admin'){const [p,u,o]=await Promise.all([rows('products'),rows('profiles'),rows('orders')]);html=`${adminNav()}<h1>Administración</h1><p class="muted">Una vista de todo lo que sucede en MAVI\'S SHOP.</p>${stats([['Usuarios',u.length],['Por aprobar',p.filter(v=>v.status==='pending').length],['Productos',p.length],['Pedidos',o.length]])}<div class="panel"><h2>Accesos de gestión</h2><div class="row"><a class="button" href="#/admin/users">Ver usuarios</a><a class="button coral" href="#/admin/products">Revisar publicaciones</a><a class="button secondary" href="#/admin/reports">Atender reportes</a></div></div>`}
else if(r==='/admin/users'){const list=await rows('profiles');const products=await rows('products');html=`${adminNav()}<h1>Usuarios registrados</h1><div class="panel scroll"><table><thead><tr><th>Usuario / ID único</th><th>Contacto</th><th>Productos</th><th>Estado</th><th>Administrar</th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.name)}</strong><p class="muted">${esc(p.customer_id)}</p></td><td>${esc(p.phone)}</td><td><a class="link" href="#/admin/products?seller=${p.id}">${products.filter(x=>x.seller_id===p.id).length} publicaciones</a></td><td>${badge(p.suspended?'Suspendido':'Activo')}${p.verified?badge('Verificado'):''}</td><td>${p.id!==user.id?`${btn(p.suspended?'Reactivar':'Suspender','suspend',p.id,'outline small')} ${btn(p.verified?'Quitar verificación':'Verificar','verify',p.id,'secondary small')}`:badge('Administrador único')}</td></tr>`).join('')}</tbody></table></div>`}
else if(r==='/admin/products'){let list=await rows('products',q=>q.order('created_at',{ascending:false}));if(query().get('seller'))list=list.filter(p=>p.seller_id===query().get('seller'));const names=await rows('seller_public');html=`${adminNav()}<h1>Publicaciones</h1>${list.length?`<div class="panel scroll"><table><thead><tr><th>Producto</th><th>Vendedor</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${list.map(p=>`<tr><td><a class="link" href="#/product/${p.id}">${esc(p.name)}</a><p>${money(p.price)}</p></td><td>${esc(names.find(n=>n.id===p.seller_id)?.name)}</td><td>${badge(p.status)}</td><td><div class="row"><a class="button small secondary" href="#/edit/${p.id}">Editar</a>${btn('Aprobar','approve',p.id,'small')}${btn('Rechazar','reject',p.id,'danger small')}${btn('Pausar','pause',p.id,'outline small')}</div></td></tr>`).join('')}</tbody></table></div>`:empty('Sin publicaciones','Aquí podrás revisar los productos de todos los usuarios.')}`}
else if(r==='/admin/settings'){html=`${adminNav()}<h1>Configuración de la tienda</h1><form id="settings" class="panel">${field('Nombre','name',settings.name,'text','required')}${field('Correo o contacto de soporte','contact',settings.contact)}${area('Categorías (una por línea)','categories',settings.categories.join('\n'))}${area('Políticas de compra, privacidad, entregas y devoluciones','policies',settings.policies)}${field('Cambiar logo e icono de pestaña','logoFile','','file','accept="image/jpeg,image/png,image/webp"')}${check('Requerir aprobación para publicar productos','approval',settings.approval)}<button>Guardar configuración</button></form>`}
else if(r==='/admin/audit'){const list=await rows('audit',q=>q.order('created_at',{ascending:false}).limit(200));html=`${adminNav()}<h1>Historial administrativo</h1><div class="panel scroll"><table><thead><tr><th>Fecha</th><th>Acción</th><th>Referencia</th></tr></thead><tbody>${list.map(a=>`<tr><td>${date(a.created_at)}</td><td>${esc(a.action)}</td><td>${esc(a.target)}</td></tr>`).join('')}</tbody></table></div>`}
else if(r==='/policies'){html=`<h1>Políticas y contacto</h1><div class="panel pre">${esc(settings.policies)}</div><div class="panel"><h2>Contacto de soporte</h2><p>${esc(settings.contact)||'El administrador aún no ha publicado un contacto de soporte.'}</p></div>`}
else if(r==='/help'){html=`<h1>¿Cómo podemos ayudarte?</h1><div class="panel">${[['¿Cómo compro?','Agrega productos al carrito y envía una solicitud. El vendedor confirma disponibilidad. Acuerda con él el pago, el costo del envío y la entrega por el chat o WhatsApp.'],['¿La página cobra mi compra?','No. La confirmación del pago la realiza manualmente el vendedor. No hay pasarela ni comisión automática.'],['¿Cómo publico?','Crea tu cuenta, confirma tu correo y entra en Mis productos. Completa los datos, fotos e inventario y envíalo a revisión.'],['¿Cómo funcionan los reclamos?','Desde Mis compras puedes solicitar una devolución para un pedido pagado. El vendedor responde y el administrador puede atender reportes. La página no ejecuta reembolsos bancarios.'],['¿Quién puede ver mis conversaciones?','Los participantes. El administrador puede revisar el texto de un chat cuando hay un reporte abierto; la revisión queda registrada.'],['¿Cómo comparto un producto?','Abre su ficha y pulsa Compartir. También puedes copiar el enlace del navegador.']].map(([q,a])=>`<details><summary>${q}</summary><p class="muted">${a}</p></details>`).join('')}</div>`}
else html=empty('Página no encontrada','Vuelve al catálogo.','<a class="button" href="#/shop">Ir a la tienda</a>');
if(g===generation){layout(html);if($('.messages'))$('.messages').scrollTop=$('.messages').scrollHeight}
}catch(e){if(g===generation)layout(`<div class="panel"><h2>No pudimos cargar esta sección</h2><p class="error">${esc(e.message)}</p>${btn('Reintentar','reload')} <a class="button secondary" href="#/shop">Volver a la tienda</a></div>`)}}
function stats(items){return `<div class="stats">${items.map(([l,v])=>`<div class="stat"><span class="muted">${l}</span><strong>${v}</strong></div>`).join('')}</div>`}
function reviewList(list){return list.length?list.map(v=>`<div class="panel"><strong>${'★'.repeat(v.rating)}${'☆'.repeat(5-v.rating)}</strong> ${badge('Pedido entregado')}<p class="pre">${esc(v.body)}</p><small class="muted">${date(v.created_at)}</small></div>`).join(''):empty('Sin opiniones todavía','Las reseñas se habilitan después de una compra entregada.')}
function orderCard(o,names){const seller=o.seller_id===user.id||admin;const buyer=o.buyer_id===user.id;return `<article class="panel"><div class="row between"><h3>Pedido ${o.id.slice(0,8).toUpperCase()}</h3>${badge(o.status)}</div><p class="muted">${date(o.created_at)} · Vendedor: ${esc(names.find(n=>n.id===o.seller_id)?.name)} · Comprador: ${esc(names.find(n=>n.id===o.buyer_id)?.name)}</p>${o.items.map(i=>`<p>${i.quantity} × ${esc(i.name)} (${esc(i.variant)}) — ${money(i.price*i.quantity)}</p>`).join('')}<strong>Total: ${money(Number(o.total)+Number(o.shipping_fee))}</strong>${o.discount>0?`<p>Descuento ${esc(o.coupon)}: −${money(o.discount)}</p>`:''}<p class="muted">Envío: ${money(o.shipping_fee)} · ${esc(o.note)}</p>${o.tracking?`<p>Seguimiento: ${esc(o.tracking)}</p>`:''}<div class="row">${seller&&o.status==='pending'?btn('Costo de envío y gastos','order-costs',o.id)+btn('Aceptar y reservar','status-accepted',o.id):''}${seller&&o.status==='accepted'?btn('Confirmar pago recibido','status-paid',o.id):''}${seller&&o.status==='paid'?btn('Marcar enviado','status-shipped',o.id):''}${['paid','shipped'].includes(o.status)?btn(buyer?'Confirmar recepción':'Marcar entregado','status-delivered',o.id):''}${o.status==='pending'||(seller&&o.status==='accepted')?btn('Cancelar','status-cancelled',o.id,'danger'):''}${buyer&&['paid','shipped','delivered'].includes(o.status)?btn('Solicitar devolución','return',o.id):''}${buyer&&o.status==='delivered'?btn('Escribir reseña','review',o.id):''}${btn('Ver historial','order-history',o.id)}${buyer?btn('Contactar vendedor','chat',o.items[0].product_id):''}</div></article>`}
function modal(html){$('#modal').innerHTML=`<button class="close secondary small" data-action="close">Cerrar</button>${html}`;$('#modal').showModal()}
document.addEventListener('submit',async e=>{const f=e.target;if(!(f instanceof HTMLFormElement))return;e.preventDefault();const b=f.querySelector('button[type=submit],button:not([type])');if(b)b.disabled=true;const fd=new FormData(f),v=Object.fromEntries(fd);try{
if(f.id==='search'){go(route()+'?'+new URLSearchParams([...fd].filter(([,v])=>v)).toString())}
else if(f.id==='auth'){if(!db)throw Error('Primero configura Supabase con la guía incluida.');const mode=f.dataset.mode;let error;if(mode==='register'){({error}=await db.auth.signUp({email:v.email,password:v.password,options:{data:{name:v.name,phone:v.phone},emailRedirectTo:location.origin+'/#/account'}}));if(error)throw error;toast('Cuenta creada. Revisa tu correo y confirma el registro.');go('/login')}
else if(mode==='forgot'){({error}=await db.auth.resetPasswordForEmail(v.email,{redirectTo:location.origin+'/#/reset'}));if(error)throw error;toast('Si el correo está registrado, recibirás un enlace de recuperación.')}
else if(mode==='reset'){({error}=await db.auth.updateUser({password:v.password}));if(error)throw error;toast('Contraseña actualizada.');go('/account')}
else{const email=v.email.trim().toLowerCase()==='admin'?env.VITE_ADMIN_EMAIL:v.email;({error}=await db.auth.signInWithPassword({email,password:v.password}));if(error)throw error;const factors=await db.auth.mfa.listFactors();const totp=factors.data?.totp?.find(x=>x.status==='verified');if(totp){modal(`<h2>Verificación en dos pasos</h2><form id="mfa-check" data-id="${totp.id}">${field('Código de 6 dígitos','code','','text','required inputmode="numeric" pattern="[0-9]{6}"')}<button>Verificar</button></form>`)}else{await authState();go('/account')}}}
else if(f.id==='profile'){const avatar=await upload(fd.get('avatarFile'))||profile.avatar;await rpc('profile',{...v,avatar,vacation:fd.has('vacation'),notifications:fd.has('notifications'),email_notifications:fd.has('email_notifications')});await authState();toast('Perfil actualizado.');await render()}
else if(f.id==='product-form'){const variants=v.variants.split('\n').filter(s=>s.trim()).map(s=>{const parts=s.split('|');const name=parts[0].trim(),stock=Number(parts[1]);if(parts.length!==2||!name||!Number.isInteger(stock)||stock<0)throw Error('Cada variante debe tener el formato Nombre | existencias enteras.');return{name,stock}});let images=fd.getAll('keepImage');const files=fd.getAll('photos').filter(f=>f.size);if(images.length+files.length>8)throw Error('Máximo 8 fotos por producto.');for(const file of files)images.push(await upload(file));await rpc('product',{...v,id:f.dataset.id,price:Number(v.price),variants,images});toast('Producto guardado.');go('/products')}
else if(f.id==='add-cart'){if(!user){go('/login');return}const p=(await rows('products',q=>q.eq('id',f.dataset.id)))[0];if(p.seller_id===user.id)throw Error('No puedes comprar tus propios productos.');const variant=p.variants.find(x=>x.name===v.variant);let old=cart.find(x=>x.product_id===p.id&&x.variant===v.variant);const qty=Number(v.quantity)+(old?.quantity||0);if(!Number.isInteger(qty)||qty>variant.stock)throw Error('La cantidad supera las existencias.');if(old)old.quantity=qty;else cart.push({product_id:p.id,name:p.name,price:p.price,seller_id:p.seller_id,variant:v.variant,quantity:Number(v.quantity)});saveCart();toast('Agregado al carrito.');await render()}
else if(f.id==='checkout'){if(!user){go('/login');return}if(!confirm('Se enviarán solicitudes con los precios actuales. El envío se acuerda con cada vendedor. ¿Continuar?'))return;await rpc('orders',{items:cart,note:v.note,coupon:v.coupon});cart=[];saveCart();toast('Solicitudes enviadas. Coordina el pago con cada vendedor.');go('/orders')}
else if(f.id==='message'){const image=await upload(fd.get('image'),'chat',f.dataset.id);if(!v.body.trim()&&!image)throw Error('Escribe un mensaje o adjunta una imagen.');await rpc('message',{conversation_id:f.dataset.id,body:v.body,image});await render()}
else if(f.id==='coupon-form'){await rpc('coupon',{...v,expires_at:new Date(v.expires_at).toISOString()});toast('Cupón creado.');await render()}
else if(f.id==='settings'){const logo=await upload(fd.get('logoFile'))||settings.logo;const categories=[...new Set(v.categories.split('\n').map(s=>s.trim()).filter(Boolean))];if(!categories.length)throw Error('Agrega al menos una categoría.');await rpc('admin_settings',{...v,categories,logo,approval:fd.has('approval')});settings=(await rows('settings'))[0];toast('Configuración guardada.');await render()}
else if(f.id==='report-form'){await rpc('report',{...v,...JSON.parse(f.dataset.context)});$('#modal').close();toast('Reporte enviado.');go('/reports')}
else if(f.id==='review-form'){await rpc('review',{order_id:f.dataset.id,...v,rating:Number(v.rating)});$('#modal').close();toast('Reseña publicada.');await render()}
else if(f.id==='costs-form'){await rpc('order_costs',{id:f.dataset.id,...v});$('#modal').close();toast('Costos actualizados.');await render()}
else if(f.id==='mfa-check'){const {error}=await db.auth.mfa.challengeAndVerify({factorId:f.dataset.id,code:v.code});if(error)throw error;$('#modal').close();await authState();toast('Verificación completada.');go('/account');await render()}
}catch(error){toast(error.message)}finally{if(b)b.disabled=false}});
document.addEventListener('change',e=>{const i=e.target.dataset.cart;if(i!==undefined){const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>999){toast('Cantidad entre 1 y 999.');return}cart[Number(i)].quantity=n;saveCart();render()}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;b.disabled=true;try{
if(a==='close'){$('#modal').close();return}if(a==='reload'){await render();return}if(a==='image'){modal(img(id,'galleryfull'));return}if(a==='share'){await navigator.clipboard.writeText(location.href);toast('Enlace copiado.');return}if(a==='cart-remove'){cart.splice(Number(id),1);saveCart();await render();return}
if(!user&&a!=='logout'){go('/login');return}
if(a==='logout'){await db.auth.signOut();user=null;profile=null;admin=false;go('/');await render();return}
if(a==='chat'){const c=await rpc('chat',{product_id:id});go('/messages?id='+c.id);return}
if(a==='favorite'){await rpc('favorite',{id});toast('Favoritos actualizados.');return}
if(a==='block'){await rpc('block',{id});toast('Preferencia de contacto actualizada.');await render();return}
if(a==='coupon-toggle'){const c=(await rows('coupons',q=>q.eq('id',id)))[0];await rpc('coupon',{...c,enabled:!c.enabled});await render();return}
if(a==='read'){await rpc('read');await render();return}
if(a.startsWith('status-')){const status=a.slice(7);if(!confirm(`¿Confirmar el estado «${labels[status]}»?${status==='paid'?' Hazlo solo después de verificar el dinero recibido.':''}`))return;let payload={id,status};if(status==='shipped'){const tracking=prompt('Empresa y número de seguimiento (opcional):','');if(tracking===null)return;payload.tracking=tracking}await rpc('order_status',payload);toast('Pedido actualizado.');await render();return}
if(a==='order-costs'){const o=(await rows('orders',q=>q.eq('id',id)))[0];modal(`<h2>Costos del pedido</h2><p class="muted">Acuerda el envío con el comprador antes de aceptar. Gastos incluye costo de mercancía y demás costos, para tu reporte.</p><form id="costs-form" data-id="${id}">${field('Envío cobrado al comprador','shipping_fee',o.shipping_fee,'number','required min="0" step="0.01"')}${field('Gastos totales registrados','expenses',o.expenses,'number','required min="0" step="0.01"')}<button>Guardar</button></form>`);return}
if(a==='order-history'){const list=await rows('order_events',q=>q.eq('order_id',id).order('created_at'));modal(`<h2>Historial del pedido</h2>${list.map(x=>`<p>${badge(x.status)} ${date(x.created_at)}</p>`).join('')}`);return}
if(a==='review'){modal(`<h2>Tu opinión cuenta</h2><form id="review-form" data-id="${id}">${select('Calificación','rating',['5','4','3','2','1'],'5')}${area('Cuéntanos tu experiencia','body')}<button>Publicar reseña</button></form>`);return}
if(a.startsWith('report-')||a==='return'){const kind=a==='return'?'return':a.slice(7),context={kind,...(kind==='chat'?{conversation_id:id}:kind==='return'?{order_id:id}:{target_id:id})};modal(`<h2>${kind==='return'?'Solicitar devolución':'Enviar reporte'}</h2><form id="report-form" data-context="${esc(JSON.stringify(context))}">${area('Motivo (mínimo 5 caracteres)','reason')}${area('Evidencia: detalles, fechas o referencias de mensajes','evidence')}<button>Enviar</button></form>`);return}
if(a==='approve'||a==='reject'||a==='pause'){await rpc('admin_product',{id,status:{approve:'approved',reject:'rejected',pause:'paused'}[a]});toast('Publicación actualizada.');await render();return}
if(a==='suspend'||a==='verify'){const p=(await rows('profiles',q=>q.eq('id',id)))[0];if(!confirm(a==='verify'?'La insignia debe reflejar una verificación real. ¿Confirmar cambio?':'¿Cambiar el estado de esta cuenta?'))return;await rpc('admin_user',{id,suspended:a==='suspend'?!p.suspended:p.suspended,verified:a==='verify'?!p.verified:p.verified});await render();return}
if(a==='resolve-report'||a==='resolve-return'){const resolution=prompt('Describe la resolución y los acuerdos de devolución o reembolso:');if(!resolution?.trim())return;await rpc(a==='resolve-report'?'admin_report':'resolve_return',{id,resolution});await render();return}
if(a==='review-chat'){const {data,error}=await db.rpc('review_report_chat',{report:id});if(error)throw error;modal(`<h2>Chat reportado</h2><p class="notice">Esta consulta quedó registrada en el historial administrativo.</p>${data.map(m=>`<div class="panel"><small>${date(m.created_at)} · ${esc(m.sender_id)}</small><p class="pre">${esc(m.body)}</p>${m.image?'<p class="muted">Mensaje con imagen privada adjunta.</p>':''}</div>`).join('')}`);return}
if(a==='mfa'){const existing=await db.auth.mfa.listFactors();if(existing.data?.totp?.some(f=>f.status==='verified')){toast('La verificación en dos pasos ya está activa.');return}for(const f of existing.data?.totp||[])if(f.status==='unverified')await db.auth.mfa.unenroll({factorId:f.id});const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'MAVI\'S SHOP'});if(error)throw error;modal(`<h2>Protege tu cuenta</h2><p>Escanea el QR con tu aplicación autenticadora y escribe el código.</p><img alt="Código QR de autenticación" src="${esc(data.totp.qr_code)}" style="max-width:220px"><form id="mfa-check" data-id="${data.id}">${field('Código de 6 dígitos','code','','text','required pattern="[0-9]{6}" inputmode="numeric"')}<button>Activar y verificar</button></form>`);return}
}catch(error){toast(error.message)}finally{b.disabled=false}});
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);render()});
let seenMessages='';setInterval(async()=>{if(!user||document.hidden||route()!=='/messages'||$('#modal').open)return;try{const c=query().get('id')||$('#message')?.dataset.id;if(!c)return;const msgs=await rows('messages',q=>q.eq('conversation_id',c).order('created_at',{ascending:false}).limit(1));const signature=msgs[0]?.id||'';if(seenMessages&&signature!==seenMessages){if(!$('#body')?.value&&!$('#image')?.files?.length)await render();else toast('Hay un nuevo mensaje. Se mostrará al enviar tu respuesta.')}seenMessages=signature}catch{}},5000);
async function init(){
const recovery=location.hash.includes('type=recovery')||route()==='/reset';
layout('<div class="load">Preparando MAVI\'S SHOP…</div>');
if(db){db.auth.onAuthStateChange((event)=>{
if(event==='PASSWORD_RECOVERY')go('/reset');
if(event==='SIGNED_OUT'){user=null;profile=null;admin=false}
if(event==='SIGNED_IN')setTimeout(()=>authState().catch(e=>toast(e.message)),0);
});
try{settings=(await rows('settings'))[0]||settings;await authState();if(recovery)go('/reset')}catch(e){toast('Revisa la configuración de Supabase: '+e.message)}}
await render();
}
init();
